<a href="https://colab.research.google.com/github/alimoorreza/CS167-sp25-notes/blob/main/Day20_MLP_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day20

## MLP using PyTorch


#### CS167: Machine Learning, Spring 2025


📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_sp25/cs167_syllabus_sp25.pdf)


In [1]:
# import torch library
import torch
import numpy as np
import torch.nn as nn


# Creating Linear Layers using PyTorch

## **Let's build a linear layer**

In [2]:
torch.manual_seed(2)                    # for reproducibility
# construction of a linear layer

input_layer_1 = nn.Linear(2, 4)

##**Inspecting the weights of a linear layer**

In [3]:
# Print the weights of the linear layer
print(f'Weights: \n{input_layer_1.weight.data}')

# Print the biases of the linear layer (if they exist)
print(f'Biases: \n{input_layer_1.bias.data}')

Weights: 
tensor([[ 0.1622, -0.1683],
        [ 0.1939, -0.0361],
        [ 0.3021,  0.1683],
        [-0.0813, -0.5717]])
Biases: 
tensor([ 0.1614, -0.6260,  0.0929,  0.0470])


## **Let's generate a random input for our linear layer and plug it into our layer**

In [15]:
# Step 1: let's generate 1 random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples     = 1
random_input          = torch.randn(number_of_samples, 2)
print(f'input numbers: \n{random_input.numpy()}\n')


# Step 2: apply forward pass through the network
output                = input_layer_1(random_input)
print(f'output layer value: \n{output.data.numpy()}\n')


input numbers: 
[[ 0.39229682 -0.22356401]]

output layer value: 
[[ 0.26269433 -0.5418888   0.17379826  0.14291513]]



In [19]:
# Step 1: let's generate 3 random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples     = 4
random_input          = torch.randn(number_of_samples, 2)
print(f'input numbers: \n{random_input.numpy()}\n')


# Step 2: apply forward pass through the network
output                = input_layer_1(random_input)
print(f'output layer value: \n{output.data.numpy()}\n')


input numbers: 
[[ 0.39229682 -0.22356401]
 [-0.31950027 -1.2050371 ]
 [ 1.0444635  -0.6332277 ]
 [ 0.57310677  0.54094744]]

output layer value: 
[[ 0.26269433 -0.5418888   0.17379826  0.14291513]
 [ 0.31239414 -0.64446425 -0.20643637  0.7618419 ]
 [ 0.4374134  -0.40063176  0.30183256  0.32410505]
 [ 0.1633755  -0.53444034  0.3571151  -0.30882734]]



##**Group Exercise#1**
Create a new Linear layer with the following structure:

> The first layer has 2 input nodes and 16 output nodes.


In [ ]:
# your code here
# ...



##**Group Exercise#2**

> Apply a tensor through your linear layer now.

> Change the value in torch.manual_seed(0) to something else, generate new inputs, and pass the tensor through your linear layer again.

> Observe the the output values.

In [ ]:
number_of_samples     = 1
random_input          = torch.randn(number_of_samples, 2)
print(f'input numbers: \n{random_input.numpy()}\n')


# Step 2: apply forward pass through the network
# your code here
# ...

print(output.data)

input numbers: 
[[0.66689056 0.42576158]]

tensor([[ 0.0119, -0.2586,  0.1606,  0.4995, -0.2540, -1.1442,  0.4086, -0.0872,
          0.0094,  0.3198,  0.7158, -0.4349, -0.0102,  0.1270,  0.3226, -0.3031]])


## **Let's add an activation function such as *ReLu(), tanh(), or sigmoid()* after your linear layer and run the experiment again to see how it changes the outputs.**

In [ ]:
# construction of a linear layer
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

input_linear_layer              = nn.Linear(2, 4)  # linear transformation module (input=2, output=4)
sigmoid_activation              = nn.Sigmoid()
tanh_activation                 = nn.Tanh()
relu_activation                 = nn.ReLU()



##**Using Sigmoid activation function**

In [ ]:
# Step 1: let's generate some random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

number_of_samples     = 1
random_X              = torch.randn(number_of_samples, 2)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# Step 2: apply forward pass through the network
output                    = input_linear_layer(random_X)
output_after_activation   = sigmoid_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('Sigmoid activation value: ')
print(output_after_activation.data.numpy())


input numbers:
[[ 0.39229682 -0.22356401]]
output layer value: 
[[ 0.26766852  0.54952395  0.11569834 -0.22820818  0.5140537  -0.24548726
  -0.34690085 -0.43468243 -0.01138236 -0.91387737  0.04074919  0.14083466
   0.07245701  0.42237854  0.21927154 -0.11810946]]
Sigmoid activation value: 
[[0.56652045 0.63402516 0.52889234 0.4431943  0.62575626 0.43893453
  0.41413417 0.39300877 0.49715444 0.28620705 0.5101859  0.5351506
  0.51810634 0.60405225 0.5545993  0.47050694]]


##**Using Tanh activation function**

In [ ]:
# Step 1: let's generate some random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

number_of_samples           = 1
num_of_neurons_input_layer  = 2
random_X                    = torch.randn(number_of_samples, num_of_neurons_input_layer)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# Step 2: apply forward pass through the network
output                    = input_linear_layer(random_X)
output_after_activation   = tanh_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('Tanh() activation value: ')
print(output_after_activation.data.numpy())


input numbers:
[[ 0.39229682 -0.22356401]]
output layer value: 
[[ 0.26766852  0.54952395  0.11569834 -0.22820818  0.5140537  -0.24548726
  -0.34690085 -0.43468243 -0.01138236 -0.91387737  0.04074919  0.14083466
   0.07245701  0.42237854  0.21927154 -0.11810946]]
Tanh() activation value: 
[[ 0.26145405  0.5001633   0.11518484 -0.22432739  0.47309762 -0.24067195
  -0.3336242  -0.40922704 -0.01138186 -0.72298807  0.04072665  0.13991086
   0.07233047  0.39893234  0.21582365 -0.1175633 ]]


##**Using ReLU activation function**

In [ ]:
# Step 1: let's generate some random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

number_of_samples           = 1
num_of_neurons_input_layer  = 2
random_X                    = torch.randn(number_of_samples, num_of_neurons_input_layer)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# Step 2: apply forward pass through the network
output                    = input_linear_layer(random_X)
output_after_activation   = relu_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('ReLU() activation value: ')
print(output_after_activation.data.numpy())


input numbers:
[[ 0.39229682 -0.22356401]]
output layer value: 
[[ 0.26766852  0.54952395  0.11569834 -0.22820818  0.5140537  -0.24548726
  -0.34690085 -0.43468243 -0.01138236 -0.91387737  0.04074919  0.14083466
   0.07245701  0.42237854  0.21927154 -0.11810946]]
ReLU() activation value: 
[[0.26766852 0.54952395 0.11569834 0.         0.5140537  0.
  0.         0.         0.         0.         0.04074919 0.14083466
  0.07245701 0.42237854 0.21927154 0.        ]]


##**Group Exercise#3**

> Experiment with different activation functions like sigmoid, tanh, and relu, and then pass a tensor through the linear layer you created for Group Exercises #1 and #2.

> Change the value in torch.manual_seed(2) to something else, generate new inputs, and pass the tensor through your linear layer again.

> Take a look at the output values and make sure they match what you were expecting!

In [ ]:
# your code here.
# ...

# your code here
# ...



raw output without tanh activation:  tensor([[-1.2720, -0.6114,  0.8026,  0.4835, -1.7741,  0.7322, -0.4001, -1.1050,
          0.6595, -0.3363, -0.7856, -0.3908, -1.0170,  0.1928,  1.0073,  0.7339]])
raw output with tanh activation:  tensor([[-0.8543, -0.5451,  0.6655,  0.4491, -0.9441,  0.6244, -0.3800, -0.8023,
          0.5780, -0.3242, -0.6559, -0.3720, -0.7686,  0.1905,  0.7646,  0.6254]])


## **Let's build the simple 1-hidden layer feedforward neural network from the lecture slides!**

<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/mlp_toy_examle_wo_weights.png" width=400/>
</div>


In [ ]:
# creation of our network
my_first_mlp = nn.Sequential(
                nn.Linear(2, 3),
                nn.Sigmoid(),
                nn.Linear(3, 1)
)

In [ ]:
# forward pass step
rand_input            = torch.randn(1, 2)
output                = my_first_mlp(rand_input)
print('final output: ', output.data)


final output:  tensor([[0.2290]])


In [ ]:
# let's make the simple 1-Hidden layer feedforwrd neural network from the lecture slides
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

# construction
num_of_neurons_input_layer      = 2
num_of_neurons_1st_hidden_layer = 3
num_of_neurons_output_layer     = 1

'''
# Alternatively, you could hardcode the values for the number of neurons directly, without using any variables such as 'num_of_neurons_input_layer ' or 'num_of_neurons_1st_hidden_layer'
input_linear_layer              = nn.Linear(2, 3)
output_linear_layer             = nn.Linear(3, 1) # linear transformation module (input=3, output=1)
'''


input_linear_layer              = nn.Linear(num_of_neurons_input_layer, num_of_neurons_1st_hidden_layer)  # linear transformation module (input=2, output=3)
relu_activation_h1              = nn.ReLU()
output_linear_layer             = nn.Linear(num_of_neurons_1st_hidden_layer, num_of_neurons_output_layer) # linear transformation module (input=3, output=1)



## **We can apply a tensor through the Linear layers now**

In [ ]:
# let's generate 2 random samples of (x1, x2) for the above linear network
torch.manual_seed(2)                                    # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples               = 1
random_X = torch.randn(number_of_samples, 2)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# apply forward pass through the network
output = input_linear_layer(random_X)
output = relu_activation(output)
print('1st-hidden layer feature map shape: ', output.shape)
output = output_linear_layer(output)
print('Output layer feature map shape: ', output.shape)


input numbers:
[[ 0.39229682 -0.22356401]]
1st-hidden layer feature map shape:  torch.Size([1, 3])
Output layer feature map shape:  torch.Size([1, 1])


## **nn.Sequential()__ module:**
You can use PyTorch's nn.Sequential module to build a network composed of multiple linear layers arranged sequentially.

In [ ]:
my_simple_network = nn.Sequential(

    nn.Linear(2, 4),
    nn.Sigmoid(),
    nn.Linear(4, 8),
    nn.Sigmoid(),
    nn.Linear(8, 1)


)

In [ ]:
# let's generate 2 random samples of (x1, x2) for the above linear network
torch.manual_seed(2)                                    # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples               = 1
random_X = torch.randn(number_of_samples, 2)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# apply forward pass through the network
output = my_simple_network(random_X)
print('Output: ', output.data)
print('Output layer feature map shape: ', output.shape)


input numbers:
[[ 0.39229682 -0.22356401]]
Output:  tensor([[-0.3476]])
Output layer feature map shape:  torch.Size([1, 1])


#**Group Exercise#4**
Let's create three Linear layers and connect them in sequence to build an MLP with the following structure:

> The first layer has 2 input nodes and 3 output nodes.

> The second layer takes 3 input nodes and outputs 6 nodes.

> The final layer connects 6 input nodes to 2 output nodes.

In [ ]:
# your code here
# ...



## **Group Exercise#5**
> Apply a tensor through your MLP now.

In [ ]:
# your code here
# ...


input: [[-0.10926431  2.050371  ]]
tensor([[ 0.9956,  0.6787, -0.6046,  0.2731, -0.8401,  1.8332]])
